// <auto-generated />
using System;
using Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20240923135844_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42dad73a-4745-4c24-b423-d0d880d804f7"),
                            Name = "Smart Phone",
                            ProductIds = "[\"5334c996-8457-4cf0-815c-ed2b77c4ff61\",\"c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914\",\"b786103d-c621-4f5a-b498-23452610f88c\"]"
                        },
                        new
                        {
                            Id = new Guid("04bb54af-5207-43ec-8541-4d4aecc1b280"),
                            Name = "White Appliances",
                            ProductIds = "[\"4f136e9f-ff8c-4c1f-9a33-d12f689bdab8\",\"6ec1297b-ec0a-4aa1-be25-6726e3b51a27\"]"
                        },
                        new
                        {
                            Id = new Guid("686ca643-87e1-46e4-82b2-96ae981f95b7"),
                            Name = "Home Kitchen",
                            ProductIds = "[\"c4bbc4a2-4555-45d8-97cc-2a99b2167bff\"]"
                        },
                        new
                        {
                            Id = new Guid("ac93c287-e185-472f-8dc0-c99b04b996de"),
                            Name = "Camera",
                            ProductIds = "[\"93170c85-7795-489c-8e8f-7dcf3b4f4188\"]"
                        },
                        new
                        {
                            Id = new Guid("e6f42685-5c79-418d-a598-f4330a3da14f"),
                            Name = "Electronics",
                            ProductIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("eb6bf803-9549-496f-b2e3-629c496a23b6"),
                            Name = "Clothing",
                            ProductIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("1f325c6d-56a6-4e04-82f6-269e05fb598f"),
                            Name = "Groceries",
                            ProductIds = "[]"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("e6f42685-5c79-418d-a598-f4330a3da14f"),
                            ProductId = new Guid("aecc6156-b310-4395-9d9a-6749b698bb00")
                        },
                        new
                        {
                            CategoryId = new Guid("e6f42685-5c79-418d-a598-f4330a3da14f"),
                            ProductId = new Guid("8eaf13b5-8572-429e-9f97-de35fd571460")
                        },
                        new
                        {
                            CategoryId = new Guid("eb6bf803-9549-496f-b2e3-629c496a23b6"),
                            ProductId = new Guid("cf1012d6-7b07-4e11-9d66-204b3bc50176")
                        },
                        new
                        {
                            CategoryId = new Guid("eb6bf803-9549-496f-b2e3-629c496a23b6"),
                            ProductId = new Guid("bdf3d2c1-5971-4252-8d74-0449971bb156")
                        },
                        new
                        {
                            CategoryId = new Guid("1f325c6d-56a6-4e04-82f6-269e05fb598f"),
                            ProductId = new Guid("60a52a21-50b3-474c-ae07-bd7dc8a1c7d2")
                        },
                        new
                        {
                            CategoryId = new Guid("1f325c6d-56a6-4e04-82f6-269e05fb598f"),
                            ProductId = new Guid("f3a81022-b44d-415f-ab8f-4519a0072164")
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61"),
                            CategoryIds = "[\"42dad73a-4745-4c24-b423-d0d880d804f7\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-1.png",
                            Name = "IPhone X",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = new Guid("c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914"),
                            CategoryIds = "[\"42dad73a-4745-4c24-b423-d0d880d804f7\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-2.png",
                            Name = "Samsung 10",
                            Price = 840.00m
                        },
                        new
                        {
                            Id = new Guid("4f136e9f-ff8c-4c1f-9a33-d12f689bdab8"),
                            CategoryIds = "[\"04bb54af-5207-43ec-8541-4d4aecc1b280\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-3.png",
                            Name = "Huawei Plus",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = new Guid("6ec1297b-ec0a-4aa1-be25-6726e3b51a27"),
                            CategoryIds = "[\"04bb54af-5207-43ec-8541-4d4aecc1b280\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-4.png",
                            Name = "Xiaomi Mi 9",
                            Price = 470.00m
                        },
                        new
                        {
                            Id = new Guid("b786103d-c621-4f5a-b498-23452610f88c"),
                            CategoryIds = "[\"42dad73a-4745-4c24-b423-d0d880d804f7\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-5.png",
                            Name = "HTC U11+ Plus",
                            Price = 380.00m
                        },
                        new
                        {
                            Id = new Guid("c4bbc4a2-4555-45d8-97cc-2a99b2167bff"),
                            CategoryIds = "[\"686ca643-87e1-46e4-82b2-96ae981f95b7\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-6.png",
                            Name = "LG G7 ThinQ",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("93170c85-7795-489c-8e8f-7dcf3b4f4188"),
                            CategoryIds = "[\"ac93c287-e185-472f-8dc0-c99b04b996de\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-6.png",
                            Name = "Panasonic Lumix",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("aecc6156-b310-4395-9d9a-6749b698bb00"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-1.png",
                            Name = "IPhone X",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = new Guid("71a085c0-8cba-4659-9502-36015d156a45"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-2.png",
                            Name = "Samsung 10",
                            Price = 840.00m
                        },
                        new
                        {
                            Id = new Guid("5578ecd9-6c6c-4426-991c-a7c6ab67a11a"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-3.png",
                            Name = "Huawei Plus",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = new Guid("c66b143d-01cf-41e9-bb12-4def24cce8ff"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-4.png",
                            Name = "Xiaomi Mi 9",
                            Price = 470.00m
                        },
                        new
                        {
                            Id = new Guid("2030fbe9-ab66-4830-885d-4e11a816739f"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-5.png",
                            Name = "HTC U11+ Plus",
                            Price = 380.00m
                        },
                        new
                        {
                            Id = new Guid("d15e3044-20cd-4685-b5f1-53aa77ae07b7"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-6.png",
                            Name = "LG G7 ThinQ",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("20eeca62-0d1e-4629-ac70-366cc013dffb"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "product-6.png",
                            Name = "Panasonic Lumix",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("8eaf13b5-8572-429e-9f97-de35fd571460"),
                            CategoryIds = "[\"e6f42685-5c79-418d-a598-f4330a3da14f\"]",
                            Description = "High performance laptop for gaming and work.",
                            Image = "laptop.jpg",
                            Name = "Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("cf1012d6-7b07-4e11-9d66-204b3bc50176"),
                            CategoryIds = "[\"eb6bf803-9549-496f-b2e3-629c496a23b6\"]",
                            Description = "Cotton t-shirt available in multiple colors.",
                            Image = "tshirt.jpg",
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("bdf3d2c1-5971-4252-8d74-0449971bb156"),
                            CategoryIds = "[\"eb6bf803-9549-496f-b2e3-629c496a23b6\"]",
                            Description = "Denim jeans that fit perfectly.",
                            Image = "jeans.jpg",
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("60a52a21-50b3-474c-ae07-bd7dc8a1c7d2"),
                            CategoryIds = "[\"1f325c6d-56a6-4e04-82f6-269e05fb598f\"]",
                            Description = "Fresh red apples.",
                            Image = "apple.jpg",
                            Name = "Apple",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = new Guid("f3a81022-b44d-415f-ab8f-4519a0072164"),
                            CategoryIds = "[\"1f325c6d-56a6-4e04-82f6-269e05fb598f\"]",
                            Description = "Whole grain bread.",
                            Image = "bread.jpg",
                            Name = "Bread",
                            Price = 2.49m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.CategoryProduct", b =>
                {
                    b.HasOne("Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
