// <auto-generated />
using System;
using Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20240923134414_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("618fd955-b75c-41b8-a7c2-82d25865498b"),
                            Name = "Smart Phone",
                            ProductIds = "[\"5334c996-8457-4cf0-815c-ed2b77c4ff61\",\"c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914\",\"b786103d-c621-4f5a-b498-23452610f88c\"]"
                        },
                        new
                        {
                            Id = new Guid("08bee5bb-d58e-4e6d-be7f-617eb463d3a6"),
                            Name = "White Appliances",
                            ProductIds = "[\"4f136e9f-ff8c-4c1f-9a33-d12f689bdab8\",\"6ec1297b-ec0a-4aa1-be25-6726e3b51a27\"]"
                        },
                        new
                        {
                            Id = new Guid("48cc1eb7-33f5-4a68-91a9-b982f14fa8c7"),
                            Name = "Home Kitchen",
                            ProductIds = "[\"c4bbc4a2-4555-45d8-97cc-2a99b2167bff\"]"
                        },
                        new
                        {
                            Id = new Guid("86e8b44b-337a-48ae-8b84-7ee4bdfa3e29"),
                            Name = "Camera",
                            ProductIds = "[\"93170c85-7795-489c-8e8f-7dcf3b4f4188\"]"
                        },
                        new
                        {
                            Id = new Guid("f81d9997-fcd4-4834-9937-7350f3d0316d"),
                            Name = "Electronics",
                            ProductIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("4abfe40d-6e05-4265-9ebe-0ed328bb4b75"),
                            Name = "Clothing",
                            ProductIds = "[]"
                        },
                        new
                        {
                            Id = new Guid("8d1027b6-e0e5-4c7f-8d8a-054fd72122f0"),
                            Name = "Groceries",
                            ProductIds = "[]"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("f81d9997-fcd4-4834-9937-7350f3d0316d"),
                            ProductId = new Guid("bc6c4ba1-62e0-44be-8cca-e4ee81318f69")
                        },
                        new
                        {
                            CategoryId = new Guid("f81d9997-fcd4-4834-9937-7350f3d0316d"),
                            ProductId = new Guid("b9d539c4-7977-45eb-b5b4-5f0d554290b7")
                        },
                        new
                        {
                            CategoryId = new Guid("4abfe40d-6e05-4265-9ebe-0ed328bb4b75"),
                            ProductId = new Guid("e269c007-202f-4a0f-94a0-efdb3e7878f6")
                        },
                        new
                        {
                            CategoryId = new Guid("4abfe40d-6e05-4265-9ebe-0ed328bb4b75"),
                            ProductId = new Guid("1dfc07f8-cf7a-4942-b1ae-7e4ecaeeeb89")
                        },
                        new
                        {
                            CategoryId = new Guid("8d1027b6-e0e5-4c7f-8d8a-054fd72122f0"),
                            ProductId = new Guid("0a03166d-27e9-4b13-ba89-e6ad1fc3b32a")
                        },
                        new
                        {
                            CategoryId = new Guid("8d1027b6-e0e5-4c7f-8d8a-054fd72122f0"),
                            ProductId = new Guid("b9d02f70-50cf-4246-a3e8-c2bb3f8f4835")
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61"),
                            CategoryIds = "[\"618fd955-b75c-41b8-a7c2-82d25865498b\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-1.png",
                            Name = "IPhone X",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = new Guid("c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914"),
                            CategoryIds = "[\"618fd955-b75c-41b8-a7c2-82d25865498b\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-2.png",
                            Name = "Samsung 10",
                            Price = 840.00m
                        },
                        new
                        {
                            Id = new Guid("4f136e9f-ff8c-4c1f-9a33-d12f689bdab8"),
                            CategoryIds = "[\"08bee5bb-d58e-4e6d-be7f-617eb463d3a6\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-3.png",
                            Name = "Huawei Plus",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = new Guid("6ec1297b-ec0a-4aa1-be25-6726e3b51a27"),
                            CategoryIds = "[\"08bee5bb-d58e-4e6d-be7f-617eb463d3a6\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-4.png",
                            Name = "Xiaomi Mi 9",
                            Price = 470.00m
                        },
                        new
                        {
                            Id = new Guid("b786103d-c621-4f5a-b498-23452610f88c"),
                            CategoryIds = "[\"618fd955-b75c-41b8-a7c2-82d25865498b\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-5.png",
                            Name = "HTC U11+ Plus",
                            Price = 380.00m
                        },
                        new
                        {
                            Id = new Guid("c4bbc4a2-4555-45d8-97cc-2a99b2167bff"),
                            CategoryIds = "[\"48cc1eb7-33f5-4a68-91a9-b982f14fa8c7\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-6.png",
                            Name = "LG G7 ThinQ",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("93170c85-7795-489c-8e8f-7dcf3b4f4188"),
                            CategoryIds = "[\"86e8b44b-337a-48ae-8b84-7ee4bdfa3e29\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            Image = "product-6.png",
                            Name = "Panasonic Lumix",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("bc6c4ba1-62e0-44be-8cca-e4ee81318f69"),
                            CategoryIds = "[\"f81d9997-fcd4-4834-9937-7350f3d0316d\"]",
                            Description = "Latest model smartphone with great features.",
                            Image = "smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = new Guid("b9d539c4-7977-45eb-b5b4-5f0d554290b7"),
                            CategoryIds = "[\"f81d9997-fcd4-4834-9937-7350f3d0316d\"]",
                            Description = "High performance laptop for gaming and work.",
                            Image = "laptop.jpg",
                            Name = "Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("e269c007-202f-4a0f-94a0-efdb3e7878f6"),
                            CategoryIds = "[\"4abfe40d-6e05-4265-9ebe-0ed328bb4b75\"]",
                            Description = "Cotton t-shirt available in multiple colors.",
                            Image = "tshirt.jpg",
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("1dfc07f8-cf7a-4942-b1ae-7e4ecaeeeb89"),
                            CategoryIds = "[\"4abfe40d-6e05-4265-9ebe-0ed328bb4b75\"]",
                            Description = "Denim jeans that fit perfectly.",
                            Image = "jeans.jpg",
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("0a03166d-27e9-4b13-ba89-e6ad1fc3b32a"),
                            CategoryIds = "[\"8d1027b6-e0e5-4c7f-8d8a-054fd72122f0\"]",
                            Description = "Fresh red apples.",
                            Image = "apple.jpg",
                            Name = "Apple",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = new Guid("b9d02f70-50cf-4246-a3e8-c2bb3f8f4835"),
                            CategoryIds = "[\"8d1027b6-e0e5-4c7f-8d8a-054fd72122f0\"]",
                            Description = "Whole grain bread.",
                            Image = "bread.jpg",
                            Name = "Bread",
                            Price = 2.49m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.CategoryProduct", b =>
                {
                    b.HasOne("Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
